"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "es" | "en";

const translations = {
  es: {
    "app.title": "Bookings Admin",
    "app.subtitle": "Plataforma de gestión de reservas y cobros",
    "app.brand": "BookFlow",
    "app.workspace": "Espacio de trabajo",

    "nav.dashboard": "Panel de Control",
    "nav.bookings": "Reservas",
    "nav.customers": "Clientes",
    "nav.payments": "Pagos",
    "nav.businesses": "Negocios",

    "header.welcome": "Bienvenido de nuevo",
    "header.avatar": "AD",

    "dashboard.title": "Resumen del Dashboard",
    "dashboard.subtitle": "Control diario de reservas, actividad y pagos.",
    "dashboard.export": "Exportar Datos",
    "dashboard.exportReport": "Exportar informe",
    "dashboard.loading": "Cargando datos del panel...",
    "dashboard.kpi.bookings": "Reservas hoy",
    "dashboard.kpi.bookings.meta": "+5 respecto a ayer",
    "dashboard.kpi.revenue": "Cobrado hoy",
    "dashboard.kpi.revenue.meta": "18 pagos registrados",
    "dashboard.kpi.pending": "Pendientes",
    "dashboard.kpi.pending.meta": "Seguimiento necesario",
    "dashboard.kpi.customers": "Clientes activos",
    "dashboard.kpi.customers.meta": "Este mes",

    "dashboard.next": "Próximas reservas",
    "dashboard.viewAll": "Ver todas",
    "dashboard.viewUpcoming": "Ver próximas",
    "dashboard.info.next": "Siguiente reserva",
    "dashboard.info.featured": "Comercio destacado",
    "dashboard.info.featured.text": "6 reservas hoy",
    "dashboard.info.reminders": "Recordatorios",
    "dashboard.info.reminders.title": "4 confirmaciones pendientes",
    "dashboard.info.reminders.text": "Revisión recomendada esta mañana",

    "payments.title": "Pagos y Cobros",
    "payments.subtitle": "Gestión de ingresos para el comercio.",
    "payments.register": "Registrar cobro",
    "payments.method.label": "Método de pago",
    "payments.method.cash": "Efectivo",
    "payments.method.card": "Tarjeta",
    "payments.method.transfer": "Transferencia",
    "payments.list": "Listado de Cobros Registrados",
    "payments.prompt.amount": "Introduce el importe del cobro:",
    "payments.prompt.customer": "Introduce el nombre del cliente:",
    "payments.select_customer": "Selecciona un cliente",
    "payments.alert.success": "Cobro registrado con éxito.",
    "payments.default_business": "Comercio General",
    "payments.delete.title": "Eliminar cobro",
    "payments.delete.text": "¿Estás seguro de que deseas eliminar este cobro?",
    "payments.delete.confirm": "Esta acción no se puede deshacer.",
    "payments.delete.action": "Eliminar",
    "payments.delete.deleting": "Eliminando...",
    "payments.delete.error": "Error al eliminar el cobro.",

    "customers.title": "Directorio de Clientes",
    "customers.subtitle": "Gestión visual de clientes.",
    "customers.new": "Nuevo cliente",
    "customers.search": "Buscar cliente...",
    "customers.loading": "Cargando clientes...",
    "customers.empty": "No se encontraron clientes.",
    "customers.error.load": "No se pudieron cargar los clientes.",
    "customers.modal.title": "Nuevo cliente",
    "customers.modal.text": "Rellena los datos para añadir un cliente al directorio.",
    "customers.form.name": "Nombre",
    "customers.form.phone": "Teléfono",
    "customers.form.email": "Email",
    "customers.form.business": "Negocio",
    "customers.form.cancel": "Cancelar",
    "customers.form.create": "Crear cliente",
    "customers.form.saving": "Guardando...",
    "customers.form.error.required": "El nombre y el negocio son obligatorios.",
    "customers.form.error.create": "Error al crear el cliente. Inténtalo de nuevo.",
    "customers.delete.text": "¿Estás seguro de que deseas eliminar este cliente?",
    "customers.delete.action": "Eliminar",
    "customers.delete.deleting": "Eliminando...",
    "customers.delete.error": "Error al eliminar el cliente.",
    "customers.delete.title": "Eliminar cliente",
    "customers.delete.confirm": "Esta acción no se puede deshacer.",
    "customers.delete.jose_warning": "No está permitido eliminar al cliente Jose.",
    "customers.view.action": "Ver detalles",
    "customers.view.title": "Detalle del cliente",
    "customers.view.text": "Información general del cliente registrado.",

    "bookings.title": "Listado de Reservas",
    "bookings.subtitle": "Gestiona las reservas de tu negocio.",
    "bookings.search": "Buscar reserva...",
    "bookings.new": "Nueva reserva",
    "bookings.total": "Total reservas",
    "bookings.total.meta": "Registros disponibles",
    "bookings.pending.meta": "Requieren seguimiento",
    "bookings.confirmed.meta": "Estado activo",
    "bookings.paid.meta": "Reservas cerradas",
    "bookings.form.title": "Nueva reserva",
    "bookings.form.date": "Fecha",
    "bookings.form.time": "Hora",
    "bookings.form.status": "Estado",
    "bookings.form.customerName": "Nombre del cliente",
    "bookings.form.customerName.placeholder": "Selecciona el cliente",
    "bookings.form.businessName": "Nombre del negocio",
    "bookings.form.businessName.placeholder": "Selecciona el negocio",
    "bookings.form.serviceName": "Servicio",
    "bookings.form.edit": "Editar reserva",
    "bookings.form.save": "Guardar cambios",
    "bookings.form.create": "Crear reserva",
    "bookings.form.success.create": "Reserva creada correctamente.",
    "bookings.form.success.update": "Reserva actualizada correctamente.",
    "bookings.form.success.delete": "Reserva eliminada correctamente.",
    "bookings.form.error.create": "No se pudo crear la reserva. Revisa los datos o el backend.",
    "bookings.form.error.resolve": "No se encontró el cliente o el negocio seleccionados.",
    "bookings.form.error.update": "No se pudo actualizar la reserva.",
    "bookings.form.error.delete": "No se pudo eliminar la reserva.",
    "bookings.delete.title": "Eliminar reserva",
    "bookings.delete.text": "¿Seguro que quieres eliminar la reserva #",
    "bookings.delete.confirm": "Esta acción no se puede deshacer.",
    "bookings.delete.action": "Eliminar",
    "bookings.delete.deleting": "Eliminando...",
    "bookings.list.title": "Reservas registradas",
    "bookings.filter.all": "Todas",

    "table.id": "ID",
    "table.customer": "Cliente",
    "table.amount": "Importe",
    "table.date": "Fecha",
    "table.status": "Estado",
    "table.action": "Acción",
    "table.time": "Hora",
    "table.business": "Comercio",
    "table.service": "Servicio",

    "action.print": "Imprimir",
    "action.show_more": "Mostrar más",
    "status.paid": "Pagado",
    "status.pending": "Pendiente",
    "status.confirmed": "Confirmada",
    "status.paid_fem": "Pagada",

    "receipt.title": "RECIBO DE PAGO",
    "receipt.bookingId": "ID Reserva",
    "receipt.thanks": "Gracias por su compra",
    "receipt.id": "ID Pago",
    "receipt.method": "Método",
    "receipt.currency": "€",

    "header.view_profile": "Ver perfil",
    "header.logout": "Cerrar sesión",
    "header.profile_menu": "Opciones de perfil",

    "profile.title": "Mi Perfil",
    "profile.subtitle": "Gestiona la información de tu cuenta",
    "profile.full_name": "Nombre Completo",
    "profile.email": "Correo Electrónico",
    "profile.birth_date": "Nombre del Negocio",
    "profile.user_role": "Rol de Usuario",
    "profile.administrator": "Administrador",
    "profile.booking_administrator": "Administrador de Reservas",
    "profile.role_admin": "Administrador del sistema",
    "profile.role_business": "Empresa",
    "profile.role_admin_detail": "Administrador del sistema",
    "profile.role_business_detail": "Empresa",

    "dashboard.compared_to_yesterday": "respecto a ayer",
    "dashboard.payment_recorded": "pago registrado",
    "dashboard.payments_recorded": "pagos registrados",
    "dashboard.no_bookings_today": "No hay reservas para hoy",
    "dashboard.no_bookings": "Sin reservas",
    "dashboard.customer_label": "Cliente",
    "dashboard.business_label": "Comercio",
    "dashboard.bookings_today": "Reservas hoy",

    "payments.customer_not_found": "Cliente #",
    "payments.alert.enter_customer": "Por favor, introduce el nombre del cliente.",
    "payments.enter_amount": "Por favor, introduce un importe válido.",

    "bookings.customer_label": "Cliente",
    "bookings.business_label": "Comercio",
    "bookings.action.edit": "Editar",
    "bookings.action.delete": "Eliminar",

    "users.no_results": "No se encontraron usuarios con ese criterio.",
    "users.empty": "Aún no hay usuarios registrados.",

    "businesses.title": "Gestión de Negocios",
    "businesses.subtitle": "Administra los comercios y negocios registrados.",
    "businesses.new": "Nuevo negocio",
    "businesses.search": "Buscar negocio...",
    "businesses.loading": "Cargando negocios...",
    "businesses.empty": "No se encontraron negocios.",
    "businesses.error.load": "No se pudieron cargar los negocios.",
    "businesses.modal.title": "Nuevo negocio",
    "businesses.modal.text": "Rellena los datos para registrar un nuevo negocio.",
    "businesses.form.name": "Nombre del negocio",
    "businesses.form.cancel": "Cancelar",
    "businesses.form.create": "Crear negocio",
    "businesses.form.saving": "Guardando...",
    "businesses.form.error.required": "El nombre del negocio es obligatorio.",
    "businesses.form.error.create": "Error al crear el negocio. Inténtalo de nuevo.",
    "businesses.delete.text": "¿Estás seguro de que deseas eliminar este negocio?",
    "businesses.delete.action": "Eliminar",
    "businesses.delete.deleting": "Eliminando...",
    "businesses.delete.error": "Error al eliminar el negocio.",
    "businesses.delete.title": "Eliminar negocio",
    "businesses.delete.confirm": "Esta acción no se puede deshacer.",
    "businesses.edit.action": "Editar",
    "businesses.edit.title": "Editar negocio",
    "businesses.edit.text": "Actualiza los datos del negocio registrado.",
    "businesses.edit.save": "Guardar cambios",
    "businesses.edit.saving": "Guardando...",
    "businesses.edit.error": "Error al editar el negocio. Inténtalo de nuevo.",

    "export.title": "Dashboard Overview",
    "export.subtitle": "Control diario de reservas, actividad y pagos.",
    "export.generated": "Generado el",
    "export.bookings_title": "Próximas reservas",
    "export.time": "Hora",
    "export.customer": "Cliente",
    "export.business": "Comercio",
    "export.service": "Servicio",
    "export.status": "Estado",
    "export.status.pending": "Pendiente",
    "export.status.confirmed": "Confirmada",
    "export.status.paid": "Pagada"
  },
  en: {
    "app.title": "Bookings Admin",
    "app.subtitle": "Booking and payment management platform",
    "app.brand": "BookFlow",
    "app.workspace": "Admin workspace",

    "nav.dashboard": "Dashboard",
    "nav.bookings": "Bookings",
    "nav.customers": "Customers",
    "nav.payments": "Payments",
    "nav.businesses": "Businesses",

    "header.welcome": "Welcome back",
    "header.avatar": "AD",

    "dashboard.title": "Dashboard Overview",
    "dashboard.subtitle": "Daily control of bookings, activity and payments.",
    "dashboard.export": "Export Data",
    "dashboard.exportReport": "Export report",
    "dashboard.loading": "Loading dashboard data...",
    "dashboard.kpi.bookings": "Bookings today",
    "dashboard.kpi.bookings.meta": "+5 from yesterday",
    "dashboard.kpi.revenue": "Collected today",
    "dashboard.kpi.revenue.meta": "18 payments recorded",
    "dashboard.kpi.pending": "Pending",
    "dashboard.kpi.pending.meta": "Follow-up required",
    "dashboard.kpi.customers": "Active customers",
    "dashboard.kpi.customers.meta": "This month",

    "dashboard.next": "Upcoming bookings",
    "dashboard.viewAll": "View all",
    "dashboard.viewUpcoming": "View upcoming",
    "dashboard.info.next": "Next booking",
    "dashboard.info.featured": "Featured business",
    "dashboard.info.featured.text": "6 bookings today",
    "dashboard.info.reminders": "Reminders",
    "dashboard.info.reminders.title": "4 pending confirmations",
    "dashboard.info.reminders.text": "Review recommended this morning",

    "payments.title": "Payments & Collections",
    "payments.subtitle": "Revenue management for commerce.",
    "payments.register": "Register payment",
    "payments.method.label": "Payment method",
    "payments.method.cash": "Cash",
    "payments.method.card": "Card",
    "payments.method.transfer": "Bank transfer",
    "payments.list": "List of Registered Payments",
    "payments.prompt.amount": "Enter the collection amount:",
    "payments.prompt.customer": "Enter the customer's name:",
    "payments.select_customer": "Select a customer",
    "payments.alert.success": "Payment registered successfully.",
    "payments.default_business": "General Commerce",
    "payments.delete.title": "Delete payment",
    "payments.delete.text": "Are you sure you want to delete this payment?",
    "payments.delete.confirm": "This action cannot be undone.",
    "payments.delete.action": "Delete",
    "payments.delete.deleting": "Deleting...",
    "payments.delete.error": "Error deleting payment.",

    "customers.title": "Customer Directory",
    "customers.subtitle": "Visual management of customers.",
    "customers.new": "New customer",
    "customers.search": "Search customer...",
    "customers.loading": "Loading customers...",
    "customers.empty": "No customers found.",
    "customers.error.load": "Could not load customers.",
    "customers.modal.title": "New customer",
    "customers.modal.text": "Fill in the details to add a customer to the directory.",
    "customers.form.name": "Name",
    "customers.form.phone": "Phone",
    "customers.form.email": "Email",
    "customers.form.business": "Business",
    "customers.form.cancel": "Cancel",
    "customers.form.create": "Create customer",
    "customers.form.saving": "Saving...",
    "customers.form.error.required": "Name and business are required.",
    "customers.form.error.create": "Error creating customer. Please try again.",
    "customers.delete.text": "Are you sure you want to delete this customer?",
    "customers.delete.action": "Delete",
    "customers.delete.deleting": "Deleting...",
    "customers.delete.error": "Error deleting customer.",
    "customers.delete.title": "Delete customer",
    "customers.delete.confirm": "This action cannot be undone.",
    "customers.delete.jose_warning": "Deleting customer Jose is not allowed.",
    "customers.view.action": "View details",
    "customers.view.title": "Customer details",
    "customers.view.text": "General information about the registered customer.",

    "bookings.title": "Bookings List",
    "bookings.subtitle": "Manage bookings for your business.",
    "bookings.search": "Search booking...",
    "bookings.new": "New booking",
    "bookings.total": "Total bookings",
    "bookings.total.meta": "Available records",
    "bookings.pending.meta": "Require follow-up",
    "bookings.confirmed.meta": "Active status",
    "bookings.paid.meta": "Closed bookings",
    "bookings.form.title": "New booking",
    "bookings.form.date": "Date",
    "bookings.form.time": "Time",
    "bookings.form.status": "Status",
    "bookings.form.customerName": "Customer name",
    "bookings.form.customerName.placeholder": "Select the customer",
    "bookings.form.businessName": "Business name",
    "bookings.form.businessName.placeholder": "Select the business",
    "bookings.form.serviceName": "Service name",
    "bookings.form.edit": "Edit booking",
    "bookings.form.save": "Save changes",
    "bookings.form.create": "Create booking",
    "bookings.form.success.create": "Booking created successfully.",
    "bookings.form.success.update": "Booking updated successfully.",
    "bookings.form.success.delete": "Booking deleted successfully.",
    "bookings.form.error.create": "Could not create the booking. Check the data or the backend.",
    "bookings.form.error.resolve": "Could not find the selected customer or business.",
    "bookings.form.error.update": "Could not update the booking.",
    "bookings.form.error.delete": "Could not delete the booking.",
    "bookings.delete.title": "Delete booking",
    "bookings.delete.text": "Are you sure you want to delete booking #",
    "bookings.delete.confirm": "This action cannot be undone.",
    "bookings.delete.action": "Delete",
    "bookings.delete.deleting": "Deleting...",
    "bookings.list.title": "Registered bookings",
    "bookings.filter.all": "All",

    "table.id": "ID",
    "table.customer": "Customer",
    "table.amount": "Amount",
    "table.date": "Date",
    "table.status": "Status",
    "table.action": "Action",
    "table.time": "Time",
    "table.business": "Business",
    "table.service": "Service",

    "action.print": "Print",
    "action.show_more": "Show more",
    "status.paid": "Paid",
    "status.pending": "Pending",
    "status.confirmed": "Confirmed",
    "status.paid_fem": "Paid",

    "receipt.title": "PAYMENT RECEIPT",
    "receipt.bookingId": "Booking ID",
    "receipt.thanks": "Thank you for your purchase",
    "receipt.id": "Payment ID",
    "receipt.method": "Method",
    "receipt.currency": "€",

    "header.view_profile": "View profile",
    "header.logout": "Logout",
    "header.profile_menu": "Profile options",

    "profile.title": "My Profile",
    "profile.subtitle": "Manage your account information",
    "profile.full_name": "Full Name",
    "profile.email": "Email Address",
    "profile.birth_date": "Business Name",
    "profile.user_role": "User Role",
    "profile.administrator": "Administrator",
    "profile.booking_administrator": "Booking Administrator",
    "profile.role_admin": "System Administrator",
    "profile.role_business": "Business",
    "profile.role_admin_detail": "System Administrator",
    "profile.role_business_detail": "Business",

    "dashboard.compared_to_yesterday": "compared to yesterday",
    "dashboard.payment_recorded": "payment recorded",
    "dashboard.payments_recorded": "payments recorded",
    "dashboard.no_bookings_today": "No bookings for today",
    "dashboard.no_bookings": "No bookings",
    "dashboard.customer_label": "Customer",
    "dashboard.business_label": "Business",
    "dashboard.bookings_today": "Bookings today",

    "payments.customer_not_found": "Customer #",
    "payments.alert.enter_customer": "Please enter the customer's name.",
    "payments.enter_amount": "Please enter a valid amount.",

    "bookings.customer_label": "Customer",
    "bookings.business_label": "Business",
    "bookings.action.edit": "Edit",
    "bookings.action.delete": "Delete",

    "users.no_results": "No users found matching that criteria.",
    "users.empty": "No users registered yet.",

    "businesses.title": "Business Management",
    "businesses.subtitle": "Manage registered businesses and commerce.",
    "businesses.new": "New business",
    "businesses.search": "Search business...",
    "businesses.loading": "Loading businesses...",
    "businesses.empty": "No businesses found.",
    "businesses.error.load": "Could not load businesses.",
    "businesses.modal.title": "New business",
    "businesses.modal.text": "Fill in the details to register a new business.",
    "businesses.form.name": "Business name",
    "businesses.form.cancel": "Cancel",
    "businesses.form.create": "Create business",
    "businesses.form.saving": "Saving...",
    "businesses.form.error.required": "Business name is required.",
    "businesses.form.error.create": "Error creating business. Please try again.",
    "businesses.delete.text": "Are you sure you want to delete this business?",
    "businesses.delete.action": "Delete",
    "businesses.delete.deleting": "Deleting...",
    "businesses.delete.error": "Error deleting business.",
    "businesses.delete.title": "Delete business",
    "businesses.delete.confirm": "This action cannot be undone.",
    "businesses.edit.action": "Edit",
    "businesses.edit.title": "Edit business",
    "businesses.edit.text": "Update the registered business details.",
    "businesses.edit.save": "Save changes",
    "businesses.edit.saving": "Saving...",
    "businesses.edit.error": "Error editing the business. Please try again.",

    "export.title": "Dashboard Overview",
    "export.subtitle": "Daily control of bookings, activity and payments.",
    "export.generated": "Generated",
    "export.bookings_title": "Upcoming bookings",
    "export.time": "Time",
    "export.customer": "Customer",
    "export.business": "Business",
    "export.service": "Service",
    "export.status": "Status",
    "export.status.pending": "Pending",
    "export.status.confirmed": "Confirmed",
    "export.status.paid": "Paid"
  }
};

type LanguageContextType = {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: keyof typeof translations.es) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>("es");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language | null;
    if (savedLang) {
      setLangState(savedLang);
      document.documentElement.setAttribute("lang", savedLang);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("language", newLang);
    document.documentElement.setAttribute("lang", newLang);
  };

  const t = (key: keyof typeof translations.es) => {
    const langMap = translations[lang] as Record<string, string>;
    return langMap[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
